import React from 'react';
import { View, Text, ScrollView, StyleSheet, TouchableOpacity } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useRouter } from 'expo-router';
import { colors, typography, spacing, borderRadius } from '../../theme';

export default function TermsScreen() {
  const router = useRouter();

  return (
    <SafeAreaView style={styles.container}>
      <View style={styles.header}>
        <TouchableOpacity onPress={() => router.back()} style={styles.backBtn}>
          <Text style={styles.backText}>{'\u2190'} Back</Text>
        </TouchableOpacity>
        <Text style={styles.title}>Terms of Service</Text>
      </View>
      <ScrollView bounces={true} overScrollMode="always" keyboardShouldPersistTaps="handled" contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
        <Text style={styles.updated}>Effective Date: March 21, 2026</Text>

        <Text style={styles.sectionTitle}>1. Acceptance of Terms</Text>
        <Text style={styles.body}>
          By downloading, installing, or using Align ("the App"), you agree to be bound by these Terms of Service. If you do not agree, please do not use the App.
        </Text>

        <Text style={styles.sectionTitle}>2. Eligibility</Text>
        <Text style={styles.body}>
          You must be at least 18 years old to use Align. By using the App, you represent that you meet this age requirement.
        </Text>

        <Text style={styles.sectionTitle}>3. Account Registration</Text>
        <Text style={styles.body}>
          You are responsible for maintaining the confidentiality of your account credentials. You agree to provide accurate birth information for chart calculations. You may update your information at any time through the Profile settings.
        </Text>

        <Text style={styles.sectionTitle}>4. Subscription Plans</Text>
        <Text style={styles.body}>
          Align offers three subscription tiers:{'\n\n'}
          {'\u2022'} Light — $9/month{'\n'}
          {'\u2022'} Premium — $29/month{'\n'}
          {'\u2022'} Pro — $49/month{'\n\n'}
          Subscriptions automatically renew unless cancelled at least 24 hours before the end of the current billing period. You can manage and cancel subscriptions through your App Store or Google Play account settings.
        </Text>

        <Text style={styles.sectionTitle}>5. Free Trial</Text>
        <Text style={styles.body}>
          If a free trial is offered, it will automatically convert to a paid subscription at the end of the trial period unless cancelled. You will not be charged during the trial.
        </Text>

        <Text style={styles.sectionTitle}>6. AI-Generated Content</Text>
        <Text style={styles.body}>
          Align uses artificial intelligence (Claude by Anthropic) to generate chart interpretations and readings. AI-generated content is for entertainment, self-reflection, and educational purposes only. It should not be considered professional advice of any kind — medical, financial, legal, or psychological.
        </Text>

        <Text style={styles.sectionTitle}>7. Financial Report Disclaimer</Text>
        <Text style={styles.body}>
          The Financial Report feature provides astrological perspectives on financial themes in your chart. This is NOT financial advice. Do not make investment, business, or financial decisions based on astrological readings. Always consult a qualified financial advisor.
        </Text>

        <Text style={styles.sectionTitle}>8. Acceptable Use</Text>
        <Text style={styles.body}>
          You agree not to:{'\n\n'}
          {'\u2022'} Use the App for any unlawful purpose{'\n'}
          {'\u2022'} Attempt to reverse-engineer or copy the App{'\n'}
          {'\u2022'} Scrape, harvest, or automate data collection{'\n'}
          {'\u2022'} Share your account credentials with others{'\n'}
          {'\u2022'} Resell or redistribute readings generated by the App
        </Text>

        <Text style={styles.sectionTitle}>9. Intellectual Property</Text>
        <Text style={styles.body}>
          All content, features, and functionality of Align — including the design, algorithms, text, graphics, and AI interpretations — are owned by Align and protected by copyright and intellectual property laws.
        </Text>

        <Text style={styles.sectionTitle}>10. Limitation of Liability</Text>
        <Text style={styles.body}>
          Align provides its services "as is" without warranties of any kind. We are not liable for any damages arising from your use of the App, including but not limited to decisions made based on astrological readings.
        </Text>

        <Text style={styles.sectionTitle}>11. Termination</Text>
        <Text style={styles.body}>
          We reserve the right to suspend or terminate your account at any time for violation of these Terms. You may delete your account at any time through the App settings.
        </Text>

        <Text style={styles.sectionTitle}>12. Governing Law</Text>
        <Text style={styles.body}>
          These Terms shall be governed by and construed in accordance with the laws of the State of Delaware, United States, without regard to conflict of law principles.
        </Text>

        <Text style={styles.sectionTitle}>13. Contact</Text>
        <Text style={styles.body}>
          For questions about these Terms, contact us at:{'\n\n'}
          support@align-astrology.com
        </Text>

        <Text style={styles.footer}>{'\u00A9'} 2026 Align. All rights reserved.</Text>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.bg.primary },
  header: { paddingHorizontal: spacing.screenPadding, paddingTop: spacing.sm, paddingBottom: spacing.md },
  backBtn: { marginBottom: spacing.sm },
  backText: { ...typography.body, color: colors.accent.primary },
  title: { ...typography.h1, color: colors.text.primary },
  content: { paddingHorizontal: spacing.screenPadding, paddingBottom: spacing.xxl },
  updated: { ...typography.caption, color: colors.accent.secondary, marginBottom: spacing.lg },
  sectionTitle: { ...typography.h4, color: colors.text.primary, marginTop: spacing.lg, marginBottom: spacing.sm },
  body: { ...typography.body, color: colors.text.secondary, lineHeight: 22 },
  footer: { ...typography.caption, color: colors.text.muted, textAlign: 'center', marginTop: spacing.xl },
});
